### PR TITLE
feat(webapp): lazy load image

### PR DESCRIPTION
**Pull request by Rotzbua**
## Changes

* Change: lazy load image
* Fix image alt text

### CODE REVIEW

**Review by nils-wisiol — CHANGES_REQUESTED** [review]
I've applied these changes but it does not lazy-load. I've confirmed that the markup is shown in the browser; but everything is loaded on page load.

**Comment by nils-wisiol** [comment]
Also, please use the `feat(webapp):` prefix for this commit

**Comment by Rotzbua** [comment]
@nils-wisiol You can throttle the network speed in the dev console to see the effect.

A good overview is: https://web.dev/browser-level-image-lazy-loading/

**Comment by nils-wisiol** [comment]
The reason I couldn't see the lazy-loading was that I used Firefox for testing. In Firefox, the only lazy-loading I see is for worldmap and worldmap marker, which is not part of this PR. In Chrome, the four logos and worldmap, worldmap marker are lazily loaded. Not sure why, they are not marked for lazy loading.

Anyways, with this PR it's better than without. Lgtm!

@Rotzbua if you want to debug the Firefox issue and/or shed some light on why the worldmap is lazily loaded, we can hold off on merging. Otherwise let's merge this soon. Waiting for your preference.

**Review by nils-wisiol — APPROVED** [review]

**Comment by Rotzbua** [comment]
@nils-wisiol found the issue: order of the attr

Seems to be an ancient Firefox bug 😠 :

   * If you define the "loading" attribute at "lazy" AFTER the "src" attribute, it has no effect (all images are loaded, even those not in the viewport).
   * If you define the "loading" attribute at "lazy" BEFORE the "src" attribute, it it applied as expected (only images in the viewport are loaded).

Source:
https://bugzilla.mozilla.org/show_bug.cgi?id=1647077

**Pull request merged**
