### PR TITLE
20201214 rfc8078

### PR DESCRIPTION
**Pull request by peterthomassen**
In preparation of RFC 8901 support. This is currently blocked by https://github.com/PowerDNS/pdns/issues/9869 and/or https://github.com/rthalley/dnspython/issues/612.

@ulrichwisser

### CODE REVIEW

**Comment by peterthomassen** [comment]
@nils-wisiol Should we add e2e tests for this functionality?

**Comment by nils-wisiol** [comment]
> Should we add e2e tests for this functionality?

yeah that'd be nice

**Comment by nils-wisiol** [comment]
Here could be a good place to do that https://github.com/desec-io/desec-stack/blob/master/test/e2e2/spec/test_api_rr_validation.py

**Comment by peterthomassen** [comment]
Closing in favor of #495. Added e2e tests there.

**Pull request closed without merging**
