### PR TITLE
feat(docs): extend LR instructions

### PR DESCRIPTION
**Pull request by barrydegraaff**
adding some text that will help new users to understand what to do to set up LE

### CODE REVIEW

**Comment by nils-wisiol** [comment]
Nice, thanks! 

Could you please change the commit title to "feat(docs): extend LR instructions"? Then it will match our regular commit message scheme.

@peterthomassen I realized that on the confirmation page for custom domains ([example](https://desec.io/custom-setup/test20201007.example)), there are no instructions on how to proceed. We should either add a token, or a link to the passwort reset form, or something.

**Comment by barrydegraaff** [comment]
@nils-wisiol changed title of PR, please let me know if you need anything else.

**Comment by nils-wisiol** [comment]
Could also change the title of the commit? Unfortunately, the title of the PR is only shown on GitHub and is not stored inside the actual git repository.

**Comment by nils-wisiol** [comment]
When merging this we should update the README at https://github.com/desec-utils/certbot-hook

**Comment by nils-wisiol** [comment]
@barrydegraaff Also, in the title I of course meant "LE" instead of "LR"

**Comment by barrydegraaff** [comment]
moving to https://github.com/desec-io/desec-stack/pull/459

**Pull request closed without merging**
