### PR TITLE
Fixed typo in code example in update-api.rst

### PR DESCRIPTION
**Pull request by vestingz**

### CODE REVIEW

**Review by peterthomassen — APPROVED** [review]
thanks!

**Comment by peterthomassen** [comment]
I'm not sure why the test status is not returning -- I already tried re-pushing. Any ideas?

@nils-wisiol

**Comment by nils-wisiol** [comment]
seeing if closing and reopening helps

**Comment by nils-wisiol** [comment]
Perhaps its related to the repo settings of @vestingz's fork?

**Comment by nils-wisiol** [comment]
@vestingz would you try opening a new PR with the same fix? I'd help us to see if this is a permanent problem or just specific to this PR. Thanks!

**Pull request closed without merging**
