### PR TITLE
fix(webapp): Fix component file name

### PR DESCRIPTION
**Pull request by Rotzbua**
* Extends #762
* Add eslint rule to prevent further mistakes
* Rename components

## Note

`vite` has a problem with `A.vue` which is compiled as `<a>` . Not sure why...
Renaming to `RecordA.vue` fixes this problem.

## Questions

- [ ] keep folder `Record` or replace by shorter `r`?

### CODE REVIEW

**Comment by Rotzbua** [comment]
To be honest, I found it more useful to spend time on migration than on finding the cause.

**Comment by peterthomassen** [comment]
Sure. - Let's get rid of the `Record` folder then, and we can go ahead.

**Review by peterthomassen — CHANGES_REQUESTED** [review]
see comment above

**Review by peterthomassen — APPROVED** [review]
lgtm

**Pull request merged**
